In [12]:
# Load packages
import numpy as np
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, average_precision_score, confusion_matrix
import sklearn.metrics as metrics
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [23]:
# load 
import numpy as np
from Extrabictree import build_bd as ebuild_bd
from Extrabictree import bdtrain as ebdtrain
from Extrabictree import bdtest as ebdtest
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import  average_precision_score
from sklearn.model_selection import KFold

In [42]:
# split rows and columns
X1kf = KFold(n_splits=5, shuffle=False)
X2kf = KFold(n_splits=5, shuffle=False) #返回的是fold数目
X1_splits = list(X1kf.split(X1))
X2_splits = list(X2kf.split(X2))

In [43]:
msleaf = 2
cs = 2
nof_trees = 10
epochs = 10 #100

# Load datasets
dataname = 'dpie'

# define method
## 'random_forest', 'logistic_regression', 'mlp_per_target', 'mlp'
method_name = 'mlp'

In [47]:
fold_count = 0
auc_dic = {}
aupr_dic = {}
for i in range(len(X1_splits)):
    for j in range(len(X2_splits)):
    
        X1_train_index, X1_test_index = X1_splits[i]
        X2_train_index, X2_test_index = X2_splits[j]

        X1_train, X1_test = X1[X1_train_index,:], X1[X1_test_index,:]
        X2_train, X2_test = X2[X2_train_index,:], X2[X2_test_index,:]

        Y_train = Y[X1_train_index,:][:,X2_train_index]
        Y_test = Y[X1_test_index,:][:,X2_test_index]

        auc_dic[fold_count] = [] 
        aupr_dic[fold_count] = [] 
        
        predtest2 = 0
        
        # model
        for z in range(nof_trees):

            chleft,chright,features2,thlist,featurelist,impuritylist,nodelist1 = ebuild_bd(X1_train,X2_train,Y_train,msleaf,cs) # building a randomized bi-clustering tree
            leafnode,leafnode2,prednode,pred,indprednode,pred_rows,pred_cols = ebdtrain(X1_train,X2_train,chleft,chright,features2,thlist,Y_train)
            leafnodetest,predtest,Ytest_vector = ebdtest(X1_test,X2_test,chleft,chright,features2,thlist,indprednode,prednode,Y_test,pred_rows,pred_cols) # Ytest is NOT used in the predictions!
            predtest2 = predtest2 + predtest # add the prediction of new tree to the previous 
            predtest = predtest2 / float(z+1)

            lr_fpr, lr_tpr, lr_thresholds = metrics.roc_curve(Ytest_vector, predtest)  # 计算ROC的值,lr_thresholds为阈值
            lr_auc = metrics.auc(lr_fpr, lr_tpr)
            print('auc:', lr_auc)
            auc_dic[fold_count].append(lr_auc)


            aupr = average_precision_score(Ytest_vector, predtest)
            print('aupr:', aupr)
            aupr_dic[fold_count].append(aupr)

        fold_count += 1
        print("===========================================") 

auc: 0.5016218199841774
aupr: 0.014869848826943062
auc: 0.5246027661014363
aupr: 0.01537733444746987
auc: 0.5167324354465128
aupr: 0.01505104864149548
auc: 0.5149859883903806
aupr: 0.014902115344379945
auc: 0.5256343351157625
aupr: 0.0153225315562253
auc: 0.5254484668248931
aupr: 0.01533133570118223
auc: 0.5291084041062595
aupr: 0.01555876940138053
auc: 0.5269744931514684
aupr: 0.015493148366567669
auc: 0.5293640921525454
aupr: 0.015417660296370126
auc: 0.5241216531793008
aupr: 0.015326177072363993
auc: 0.4604881014229226
aupr: 0.024531801478015782
auc: 0.4168849395330043
aupr: 0.02296640323882951
auc: 0.380360312581176
aupr: 0.022042483464499066
auc: 0.3723326213909814
aupr: 0.02166037048140021
auc: 0.3602232877305394
aupr: 0.02125866749898404
auc: 0.3514762882308232
aupr: 0.021084185103490406
auc: 0.3486140875592884
aupr: 0.02077665970865196
auc: 0.3436677718609596
aupr: 0.020680034115189583
auc: 0.3407018464802148
aupr: 0.020623620003036514
auc: 0.3863106533995247
aupr: 0.0195114566

In [3]:
def load_data(dataname):
    if dataname in ['ERN', 'SRN']:
        X1 = np.loadtxt('./dataset/'+str(dataname)+'/X1.txt',delimiter=",")
        Y = np.loadtxt('./dataset/'+str(dataname)+'/Y.txt',delimiter=",")
        X2 = np.loadtxt('./dataset/'+str(dataname)+'/X2.txt',delimiter=",")
    else:
        X1 = np.loadtxt('./dataset/'+str(dataname)+'/'+str(dataname)+'_X1.txt')
        Y = np.loadtxt('./dataset/'+str(dataname)+'/'+str(dataname)+'_Y.txt')
        X2 = np.loadtxt('./dataset/'+str(dataname)+'/'+str(dataname)+'_X2.txt')
    return X1, X2, Y

In [4]:
X1, X2, Y = load_data(dataname)
print(Y)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
shuffled = [True, False]

In [12]:
setting = 'B'
if setting == 'C':
    X1, Y = X2, np.transpose(Y)

In [13]:
for item in shuffled:
    
    metrics_to_calculate = ['auroc', 'aupr']
    metric_values_per_fold = {}
    if 'auroc' in metrics_to_calculate:
        metric_values_per_fold['auroc_micro'] = []
        metric_values_per_fold['auroc_macro'] = []
    if 'aupr' in metrics_to_calculate:
        metric_values_per_fold['aupr_micro'] = []
        metric_values_per_fold['aupr_macro'] = []

    kf = KFold(n_splits=10, shuffle=item,random_state=42)
    fold_counter = 0

    for train_index, test_index in kf.split(X1):
        print('======================= Fold '+str(fold_counter)+' =========================================')

        # split the dataset
        X_train, X_test = X1[train_index], X1[test_index]
        y_train, y_test = Y[train_index], Y[test_index]
        
        # scaler
        scaler = None
        if scale_type == 'standard':
            scaler = StandardScaler()
        elif scale_type == 'minmax':
            scaler = MinMaxScaler()
        if scaler is not None:
            scaler.fit(X_train)
            X_train = scaler.transform(X_train)
            X_test = scaler.transform(X_test)

        clf = None
        # define the oneVSrest classifier with the base classifier
        if method_name == 'random_forest':
            clf = OneVsRestClassifier(RandomForestClassifier())
        elif method_name == 'logistic_regression':
            clf = OneVsRestClassifier(LogisticRegression(random_state=0))
        elif method_name == 'mlp_per_target':
            clf = OneVsRestClassifier(MLPClassifier(random_state=1, hidden_layer_sizes=(256), solver='adam', learning_rate='adaptive', max_iter=300)) # binary relevance approach that uses a neural network as the base classifier (so it creates as many neural networks as there are labels)
        elif method_name == 'mlp':
            clf = MLPClassifier(random_state=1, hidden_layer_sizes=(512), solver='adam', learning_rate='adaptive', max_iter=300) # standard neural network
        else:
            raise ValueError("invalid method name given")
            
        # fit the classifier on the training set
        clf.fit(X_train, y_train)

        # generate probability predictions for every sample in the test set
        y_pred = clf.predict_proba(X_test)

        print(str(y_pred.shape))

        # calculate the performance metrics on the test set
        if 'auroc' in metrics_to_calculate:
            metric_values_per_fold['auroc_micro'].append(roc_auc_score(y_test, y_pred, average='micro'))

            # This is not really important as we are only interested in the micro measures.
            # Nevertheless, I basically do the macro averaging by hand so that I can skip labels that have only samples with one class
            roc_auc_per_label = []
            for label_idx in range(Y.shape[1]): # 0是行 1是列
                if len(set(y_test[:, label_idx])) >= 2: # here test is validation
                    roc_auc_per_label.append(roc_auc_score(y_test[:, label_idx], y_pred[:, label_idx]))
            print(str(len(roc_auc_per_label))+' out of the '+str(y_test.shape[1])+' total labels has more than one classes present')

            metric_values_per_fold['auroc_macro'].append(np.mean(roc_auc_per_label))


        if 'aupr' in metrics_to_calculate:
            metric_values_per_fold['aupr_micro'].append(average_precision_score(y_test, y_pred, average='micro'))

            aupr_per_label = []
            for label_idx in range(Y.shape[1]):
                if len(set(y_test[:, label_idx])) >= 2:
                    aupr_per_label.append(average_precision_score(y_test[:, label_idx], y_pred[:, label_idx]))

            metric_values_per_fold['aupr_macro'].append(np.mean(aupr_per_label))


        fold_counter += 1
        print('========================================================================')
        print('')
        
    # calculate the mean and std for every metric measured during training and validation
    print('setting' + str(setting), str(dataname), str(method_name), 'shuffle = ' + str(item))
    for metric_name in metric_values_per_fold.keys():
        print(metric_name+': '+ str('%.4f' % np.mean(metric_values_per_fold[metric_name])) +' ('+ str('%.4f' % np.std(metric_values_per_fold[metric_name])) +')')
        print('')

======================= Fold 0 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(21, 210)
72 out of the 210 total labels has more than one classes present

======================= Fold 1 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(21, 210)
82 out of the 210 total labels has more than one classes present

======================= Fold 2 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(21, 210)
96 out of the 210 total labels has more than one classes present

======================= Fold 3 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(21, 210)
42 out of the 210 total labels has more than one classes present

======================= Fold 4 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(20, 210)
76 out of the 210 total labels has more than one classes present

======================= Fold 5 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(20, 210)
88 out of the 210 total labels has more than one classes present

======================= Fold 6 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(20, 210)
99 out of the 210 total labels has more than one classes present

======================= Fold 7 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(20, 210)
89 out of the 210 total labels has more than one classes present

======================= Fold 8 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(20, 210)
72 out of the 210 total labels has more than one classes present

======================= Fold 9 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_split.py:293: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  warnings.warn(


(20, 210)
53 out of the 210 total labels has more than one classes present

settingB dpii mlp shuffle = True
auroc_micro: 0.9327 (0.0332)

auroc_macro: 0.9151 (0.0433)

aupr_micro: 0.8303 (0.0494)

aupr_macro: 0.8308 (0.0614)

======================= Fold 0 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(21, 210)
52 out of the 210 total labels has more than one classes present

======================= Fold 1 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(21, 210)
39 out of the 210 total labels has more than one classes present

======================= Fold 2 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(21, 210)
36 out of the 210 total labels has more than one classes present

======================= Fold 3 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(21, 210)
45 out of the 210 total labels has more than one classes present

======================= Fold 4 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(20, 210)
32 out of the 210 total labels has more than one classes present

======================= Fold 5 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(20, 210)
42 out of the 210 total labels has more than one classes present

======================= Fold 6 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(20, 210)
50 out of the 210 total labels has more than one classes present

======================= Fold 7 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(20, 210)
64 out of the 210 total labels has more than one classes present

======================= Fold 8 =========================================


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


(20, 210)
35 out of the 210 total labels has more than one classes present

======================= Fold 9 =========================================
(20, 210)
65 out of the 210 total labels has more than one classes present

settingB dpii mlp shuffle = False
auroc_micro: 0.7850 (0.1375)

auroc_macro: 0.6989 (0.1682)

aupr_micro: 0.5828 (0.1806)

aupr_macro: 0.5870 (0.1837)



/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
